// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkfcVtNcyDlW0yiTH2i5rYdmBJ_z1O57M',
    appId: '1:246498824596:web:efc2c0cbc94999559d3f81',
    messagingSenderId: '246498824596',
    projectId: 'firescout3824',
    authDomain: 'firescout3824.firebaseapp.com',
    databaseURL: 'https://firescout3824-default-rtdb.firebaseio.com',
    storageBucket: 'firescout3824.appspot.com',
    measurementId: 'G-7SBQ64VMNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-7YERZcuUO380l57RZ7UqnoRpn2BBpg',
    appId: '1:246498824596:android:c986963e31d463689d3f81',
    messagingSenderId: '246498824596',
    projectId: 'firescout3824',
    databaseURL: 'https://firescout3824-default-rtdb.firebaseio.com',
    storageBucket: 'firescout3824.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-cr2Lnbx_JWqv49kYWD7usMh6t0I83V8',
    appId: '1:246498824596:ios:f6473067d14216059d3f81',
    messagingSenderId: '246498824596',
    projectId: 'firescout3824',
    databaseURL: 'https://firescout3824-default-rtdb.firebaseio.com',
    storageBucket: 'firescout3824.appspot.com',
    iosClientId: '246498824596-b3cu10rjs22llm6vk4sb7pi0blega0fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoutingApp2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-cr2Lnbx_JWqv49kYWD7usMh6t0I83V8',
    appId: '1:246498824596:ios:f6473067d14216059d3f81',
    messagingSenderId: '246498824596',
    projectId: 'firescout3824',
    databaseURL: 'https://firescout3824-default-rtdb.firebaseio.com',
    storageBucket: 'firescout3824.appspot.com',
    iosClientId: '246498824596-b3cu10rjs22llm6vk4sb7pi0blega0fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoutingApp2023',
  );
}
